name: enviro
description: A build_runner compatible package that generates type-safe environment configuration from .env files with multi-environment support.
version: 1.0.0
homepage: https://github.com/ijashuzain/enviro

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: '>=2.4.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.0
  source_gen: ^1.5.0
  analyzer: ^6.0.0
  lints: ^3.0.0
  test: ^1.24.0